### PR TITLE
Find release by DiscID with updated RSpec

### PR DESCRIPTION
**Pull request by jvoegele**
This Pull Request replaces @danbee's #26 and builds on top of my own #31 to add the capability to find releases by DiscID.

### CODE REVIEW

**Comment by localhots** [comment]
This build currently fails, can you fix [the errors](https://travis-ci.org/localhots/musicbrainz/jobs/54351766) please?

**Comment by jvoegele** [comment]
Looking into the build failures now.

**Comment by jvoegele** [comment]
I think the build failures might have been due to a temporary service disruption at MusicBrainz. I ran the tests in `master` branch locally and they failed the same way, then later started passing again. I've now re-run the tests locally for this `feature/find-release-by-discid` and they are passing now. Could you kick off a new Travis build and see if the problem has gone away?

**Comment by jvoegele** [comment]
That said, I think my next step is to use the `VCR` gem to isolate the tests from the MusicBrainz service. This will allow for full integration testing, but by using VCR to capture the results we wouldn't need a live connection to MusicBrainz to run the tests thereafter.

**Comment by jvoegele** [comment]
By closing and reopening this pull request I was able to trigger a new Travis build and as I suspected the build is passing again.

**Comment by localhots** [comment]
You're right, @jvoegele, the tests are green now. Thanks for your contribution.

**Pull request merged**
