### PR TITLE
Fix recording search

### PR DESCRIPTION
**Pull request by tomwolfe**
MusicBrainz::Recording.search("Track title", "artist name") now works and is tested in spec/models/recording_spec.rb

Moved from Track.search to Recording.search since the name change should remove a bunch of cruft in BaseModel.search (I want to say this is the factory design pattern).

Sorry it took me so long to fix what I broke. Thanks!
rspec:
42 examples, 0 failures

### CODE REVIEW

**Comment by diegodurs** [comment]
:+1: 
ping me if you need help to merge this!

**Comment by localhots** [comment]
This branch should be rabased to master in order to be merged

**Comment by diegodurs** [comment]
sure but I don't know how to do that without creating a new PR.
Would that works for you ?

**Comment by localhots** [comment]
Feel free to fork this branch and create a new PR — I see no problem doing that. We already missed the moment here.

**Comment by localhots** [comment]
Merged in https://github.com/localhots/musicbrainz/pull/33

**Pull request closed without merging**
